apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hvtq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-hvtq@sha256:3776a919da1af44134c087e2a5d840f7a5d9e7fd653e1c0061ff48388d33dccc
        name: my-nodejs
        resources: {}
status: {}
